using FluentAssertions;

namespace FluentDOM.Tests
{
    public static class Extensions
    {
        public static void ShouldBeLike(this string source, string expectedSource)
        {
            void DeleteAll(ref string str, params string[] whoArr)
            {
                foreach (var who in whoArr)
                {
                    while (str.Contains(who))
                    {
                        str = str.Replace(who, string.Empty);
                    }
                }
            }
            source = source.Replace(@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------", "");
            source = source.Trim();
            expectedSource = expectedSource.Trim();
            
            DeleteAll(ref source,"\r","\t","\n"," ");;
            DeleteAll(ref expectedSource, "\r","\t","\n"," ");;

            source.Should().Be(expectedSource);
        }
    }
}