//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleProject {
    using System;
    using System.Threading.Tasks;
    
    
    public class ResponseModel<T>
     {
        
        public T Data;
        
        public static ResponseModel<T> Success(T data) {
            return new ResponseModel<T>();
        }
    }
    
    public class AbstractCommand<TResponse>
     {
        
        private System.Guid _id;
        
        public AbstractCommand(System.Guid id) {
            this._id = id;
        }
        
        private System.Guid Id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
    }
    
    public interface ICommandHandler<TCommand, TResponse>
        where TCommand : AbstractCommand<TResponse>
     {
        
        ResponseModel<TResponse> Handle(TCommand command);
    }
    
    public class LoginCommandHandler : ICommandHandler<LoginCommand_1, string> {
        
        public ResponseModel<string> Handle(LoginCommand_1 command) {
            if ((command == null)) {
                throw new System.ArgumentNullException("command");
            }
            if (((command.Username1 == "admin") 
                        && (command.Password1 == "admin"))) {
                return ResponseModel<string>.Success("Welcome");
            }
            else {
                throw new System.Exception("invalid username or password");
            }
        }
    }
    
    public class LoginCommand_0 : AbstractCommand<string> {
        
        private string _username0;
        
        private string _password0;
        
        public LoginCommand_0(System.Guid id0, string username0, string password0) : 
                base(id0) {
            this._username0 = username0;
            this._password0 = password0;
        }
        
        public string Username0 {
            get {
                return this._username0;
            }
            set {
                this._username0 = value;
            }
        }
        
        public string Password0 {
            get {
                return this._password0;
            }
            set {
                this._password0 = value;
            }
        }
    }
    
    public class LoginCommand_1 : AbstractCommand<string> {
        
        private string _username1;
        
        private string _password1;
        
        public LoginCommand_1(System.Guid id1, string username1, string password1) : 
                base(id1) {
            this._username1 = username1;
            this._password1 = password1;
        }
        
        public string Username1 {
            get {
                return this._username1;
            }
            set {
                this._username1 = value;
            }
        }
        
        public string Password1 {
            get {
                return this._password1;
            }
            set {
                this._password1 = value;
            }
        }
    }
    
    public class LoginCommand_2 : AbstractCommand<string> {
        
        private string _username2;
        
        private string _password2;
        
        public LoginCommand_2(System.Guid id2, string username2, string password2) : 
                base(id2) {
            this._username2 = username2;
            this._password2 = password2;
        }
        
        public string Username2 {
            get {
                return this._username2;
            }
            set {
                this._username2 = value;
            }
        }
        
        public string Password2 {
            get {
                return this._password2;
            }
            set {
                this._password2 = value;
            }
        }
    }
    
    public class LoginCommand_3 : AbstractCommand<string> {
        
        private string _username3;
        
        private string _password3;
        
        public LoginCommand_3(System.Guid id3, string username3, string password3) : 
                base(id3) {
            this._username3 = username3;
            this._password3 = password3;
        }
        
        public string Username3 {
            get {
                return this._username3;
            }
            set {
                this._username3 = value;
            }
        }
        
        public string Password3 {
            get {
                return this._password3;
            }
            set {
                this._password3 = value;
            }
        }
    }
    
    public class LoginCommand_4 : AbstractCommand<string> {
        
        private string _username4;
        
        private string _password4;
        
        public LoginCommand_4(System.Guid id4, string username4, string password4) : 
                base(id4) {
            this._username4 = username4;
            this._password4 = password4;
        }
        
        public string Username4 {
            get {
                return this._username4;
            }
            set {
                this._username4 = value;
            }
        }
        
        public string Password4 {
            get {
                return this._password4;
            }
            set {
                this._password4 = value;
            }
        }
    }
}
