using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SampleProject
{
    class Program
    {
        static void Main(string[] args)
        {
            //using autogenerated codes
            LoginCommand_1 cmd = new LoginCommand_1(Guid.NewGuid(), "admin", "admin");
            var handler=new LoginCommandHandler();
            var result = handler.Handle(cmd);
        }
    }
}
